package {{package.name}}.crud;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
{{entity.imports}}
import java.time.Instant;
import java.util.UUID;

/**
 * Plain row for table {@code {{table.name}}} (manifest v1, ADR-0036). The primary key is
 * generated by PostgreSQL (uuidv7() default); the application never fabricates identities.
 */
@TableName("{{table.name}}")
public class {{entity.className}}Entity {

    @TableId(type = IdType.INPUT)
    private UUID id;

{{entity.fields}}

    private Instant createdAt;

    private Instant updatedAt;

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }
{{entity.accessors}}

    public Instant getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Instant updatedAt) {
        this.updatedAt = updatedAt;
    }
}