package dev.ainer.module.identity.account.application;

import dev.ainer.core.error.ErrorCode;

public enum IdentityErrorCode implements ErrorCode {
    INVALID_PROVISIONING_REQUEST("AINER.IDENTITY.INVALID_PROVISIONING_REQUEST", "身份初始化参数不合法", 422),
    INVALID_IDENTITY_REFERENCE("AINER.IDENTITY.INVALID_IDENTITY_REFERENCE", "身份引用不合法", 422),
    INVALID_DIRECTORY_QUERY("AINER.IDENTITY.INVALID_DIRECTORY_QUERY", "身份目录查询参数不合法", 422),
    DIRECTORY_MEMBER_NOT_FOUND("AINER.IDENTITY.DIRECTORY_MEMBER_NOT_FOUND", "身份目录成员不存在", 404),
    ALREADY_EXISTS("AINER.IDENTITY.ALREADY_EXISTS", "租户代码或用户名已经存在", 409),
    ACCOUNT_NOT_FOUND("AINER.IDENTITY.ACCOUNT_NOT_FOUND", "身份账号不存在", 404),
    MEMBERSHIP_NOT_FOUND("AINER.IDENTITY.MEMBERSHIP_NOT_FOUND", "租户成员关系不存在", 404),
    MEMBER_ALREADY_EXISTS("AINER.IDENTITY.MEMBER_ALREADY_EXISTS", "该用户已经是租户成员", 409),
    INVALID_MEMBER_REQUEST("AINER.IDENTITY.INVALID_MEMBER_REQUEST", "租户成员操作参数不合法", 422),
    MEMBER_STATE_CONFLICT("AINER.IDENTITY.MEMBER_STATE_CONFLICT", "租户成员状态不允许执行该操作", 409),
    CANNOT_MODIFY_OWNER(
            "AINER.IDENTITY.CANNOT_MODIFY_OWNER", "租户所有者不能通过成员接口变更或移除", 409),
    OWNER_REVOCATION_REQUIRES_TRANSFER(
            "AINER.IDENTITY.OWNER_REVOCATION_REQUIRES_TRANSFER", "撤销租户所有者前必须先转移所有权", 409),
    ACCESS_STATE_CONFLICT("AINER.IDENTITY.ACCESS_STATE_CONFLICT", "身份访问状态已发生变化", 409),
    TENANT_BOOTSTRAP_STATE_CONFLICT(
            "AINER.IDENTITY.TENANT_BOOTSTRAP_STATE_CONFLICT", "租户初始化状态与配置不一致", 409),
    INVALID_TENANT_PROVISIONING_REQUEST(
            "AINER.IDENTITY.INVALID_TENANT_PROVISIONING_REQUEST", "租户供应请求参数不合法", 422),
    TENANT_PROVISIONING_NOT_FOUND(
            "AINER.IDENTITY.TENANT_PROVISIONING_NOT_FOUND", "租户供应请求不存在", 404),
    TENANT_PROVISIONING_IDEMPOTENCY_CONFLICT(
            "AINER.IDENTITY.TENANT_PROVISIONING_IDEMPOTENCY_CONFLICT",
            "幂等键已被不同的租户供应请求占用", 409),
    TENANT_PROVISIONING_CONFLICT(
            "AINER.IDENTITY.TENANT_PROVISIONING_CONFLICT", "租户或待激活用户已被占用", 409),
    TENANT_PROVISIONING_USER_CONFLICT(
            "AINER.IDENTITY.TENANT_PROVISIONING_USER_CONFLICT", "目标用户状态不允许供应租户", 409),
    TENANT_PROVISIONING_STATE_CONFLICT(
            "AINER.IDENTITY.TENANT_PROVISIONING_STATE_CONFLICT", "租户供应请求状态已发生变化", 409),
    TENANT_ACTIVATION_CREDENTIAL_INVALID(
            "AINER.IDENTITY.TENANT_ACTIVATION_CREDENTIAL_INVALID", "租户激活凭据无效", 401),
    TENANT_ACTIVATION_PASSWORD_INVALID(
            "AINER.IDENTITY.TENANT_ACTIVATION_PASSWORD_INVALID", "初始密码不符合安全要求", 422),
    TENANT_PROVISIONING_ACCEPTANCE_FORBIDDEN(
            "AINER.IDENTITY.TENANT_PROVISIONING_ACCEPTANCE_FORBIDDEN", "不能接受该租户供应请求", 403),
    NOTIFICATION_LEASE_LOST(
            "AINER.IDENTITY.NOTIFICATION_LEASE_LOST", "身份通知投递租约已经失效", 409),
    INVALID_NOTIFICATION_RECEIPT(
            "AINER.IDENTITY.INVALID_NOTIFICATION_RECEIPT", "身份通知投递回执参数不合法", 422),
    NOTIFICATION_RECEIPT_NOT_FOUND(
            "AINER.IDENTITY.NOTIFICATION_RECEIPT_NOT_FOUND", "身份通知不存在", 404),
    NOTIFICATION_RECEIPT_STATE_CONFLICT(
            "AINER.IDENTITY.NOTIFICATION_RECEIPT_STATE_CONFLICT", "身份通知尚未被网关接收", 409),
    NOTIFICATION_RECEIPT_IDEMPOTENCY_CONFLICT(
            "AINER.IDENTITY.NOTIFICATION_RECEIPT_IDEMPOTENCY_CONFLICT",
            "身份通知投递回执已经记录不同终态", 409),
    ACCESS_EVENT_LEASE_LOST(
            "AINER.IDENTITY.ACCESS_EVENT_LEASE_LOST", "身份访问事件租约已经失效", 409),
    INVALID_RECOVERY_REQUEST(
            "AINER.IDENTITY.INVALID_RECOVERY_REQUEST", "身份恢复请求不合法", 422),
    ACCESS_EVENT_NOT_EXHAUSTED(
            "AINER.IDENTITY.ACCESS_EVENT_NOT_EXHAUSTED", "身份访问事件不是可重放的耗尽状态", 409),
    REPLAY_REQUEST_NOT_FOUND(
            "AINER.IDENTITY.REPLAY_REQUEST_NOT_FOUND", "身份访问事件重放请求不存在", 404),
    REPLAY_REQUEST_CONFLICT(
            "AINER.IDENTITY.REPLAY_REQUEST_CONFLICT", "身份访问事件重放请求状态已变化", 409),
    REPLAY_APPROVER_MUST_DIFFER(
            "AINER.IDENTITY.REPLAY_APPROVER_MUST_DIFFER", "重放批准者必须与申请者不同", 409),
    REPLAY_REQUEST_EXPIRED(
            "AINER.IDENTITY.REPLAY_REQUEST_EXPIRED", "身份访问事件重放请求已过期", 409);

    private final String code;
    private final String defaultMessage;
    private final int httpStatus;

    IdentityErrorCode(String code, String defaultMessage, int httpStatus) {
        this.code = code;
        this.defaultMessage = defaultMessage;
        this.httpStatus = httpStatus;
    }

    @Override
    public String code() {
        return code;
    }

    @Override
    public String defaultMessage() {
        return defaultMessage;
    }

    @Override
    public int httpStatus() {
        return httpStatus;
    }
}
