wrapperVersion=3.3.4
distributionType=only-script
distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/4.0.0-rc-6/apache-maven-4.0.0-rc-6-bin.zip
distributionSha256Sum=4d42c5b7c3366f0c4a02375c09e4c00e7b1d9ff21d3772b321d5dfaf932b7f79
