<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>dev.ainer</groupId>
        <artifactId>ainer-boot</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>ainer-framework</artifactId>
    <packaging>pom</packaging>
    <name>Ainer Framework</name>

    <modules>
        <module>ainer-core</module>
        <module>ainer-spring</module>
        <module>ainer-security</module>
        <module>ainer-starter-web</module>
        <module>ainer-starter-persistence</module>
        <module>ainer-starter-security</module>
    </modules>
</project>
