#!/usr/bin/env bash
set -euo pipefail

boot_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
producer_wrapper="$boot_root/mvnw"
artifact_source="${AINER_ARTIFACT_SOURCE:-local}"
maven_settings="${AINER_MAVEN_SETTINGS:-}"

fail() {
  echo "[ainer-initializer-consumer] ERROR: $*" >&2
  exit 1
}

configured_version="$(
  sed -n 's:.*<revision>\([^<]*\)</revision>.*:\1:p' "$boot_root/pom.xml" \
    | sed -n '1p'
)"
ainner_version="${AINER_VERSION:-$configured_version}"
[[ -n "$ainner_version" ]] \
  || fail "cannot determine the Ainer version; set AINER_VERSION explicitly"

case "$artifact_source" in
  local|remote) ;;
  *) fail "AINER_ARTIFACT_SOURCE must be local or remote (got: $artifact_source)" ;;
esac
if [[ "$artifact_source" == "remote" && "$ainner_version" == *-SNAPSHOT ]]; then
  fail "remote initializer verification requires a non-SNAPSHOT AINER_VERSION"
fi

maven_settings_args=()
if [[ -n "$maven_settings" ]]; then
  [[ -f "$maven_settings" ]] || fail "Maven settings file is missing: $maven_settings"
  maven_settings_args=(--settings "$maven_settings")
elif [[ "$artifact_source" == "remote" ]]; then
  fail "remote initializer verification requires AINER_MAVEN_SETTINGS"
fi

[[ -x "$producer_wrapper" ]] \
  || fail "producer Maven Wrapper is missing or not executable: $producer_wrapper"

temporary_parent="${TMPDIR:-/tmp}"
temporary_dir="$(mktemp -d "$temporary_parent/ainer-initializer-consumer.XXXXXX")"
local_repository="$temporary_dir/repository"
generated_dir="$temporary_dir/generated"
manifest="$temporary_dir/manifest.yaml"
cli_jar="$temporary_dir/initializer-cli.jar"

cleanup() {
  case "$temporary_dir" in
    "$temporary_parent"/ainer-initializer-consumer.*)
      rm -rf -- "$temporary_dir"
      ;;
    *)
      echo "[ainer-initializer-consumer] refusing unsafe cleanup target: $temporary_dir" >&2
      ;;
  esac
}
trap cleanup EXIT

cd "$boot_root"
if [[ "$artifact_source" == "local" ]]; then
  "$producer_wrapper" --batch-mode --no-transfer-progress \
    "${maven_settings_args[@]}" \
    -Dmaven.repo.local="$local_repository" \
    -Drevision="$ainner_version" \
    -Dgpg.skip=true \
    -DskipTests \
    clean install
else
  [[ ! -e "$local_repository/dev/ainer" ]] \
    || fail "remote initializer repository must start without Ainer artifacts"
  "$producer_wrapper" --batch-mode --no-transfer-progress \
    "${maven_settings_args[@]}" \
    -Dmaven.repo.local="$local_repository" \
    org.apache.maven.plugins:maven-dependency-plugin:3.8.1:copy \
    -Dartifact="dev.ainer:ainer-initializer-cli:$ainner_version:jar:cli" \
    -DoutputDirectory="$temporary_dir"
fi

# 1. Deterministic generation: the same manifest must produce byte-identical output twice.
cat >"$manifest" <<EOF
schemaVersion: v1
project:
  name: Initializer Consumer Gate
  groupId: dev.ainer.consumer
  artifactId: initializer-gate
  version: 1.0.0
  description: generated by the Ainer Project Initializer gate
spring-boot: 4.1.1
ainner: $ainner_version
java: 25
package: dev.ainer.consumer.gate
EOF

if [[ "$ainner_version" == *-SNAPSHOT ]]; then
  printf 'allowSnapshot: true\n' >>"$manifest"
fi

if [[ "$artifact_source" == "local" ]]; then
  cli_jar="$(find "$local_repository/dev/ainer/ainer-initializer-cli" -name '*-cli.jar' | head -n 1)"
else
  cli_jar="$(find "$temporary_dir" -maxdepth 1 -name '*-cli.jar' | head -n 1)"
fi
[[ -n "$cli_jar" ]] || fail "ainner-initializer-cli shaded JAR was not resolved"

run_cli() {
  java -jar "$cli_jar" "$@"
}

reject_ainer_source_copies() {
  local source_root="$1"
  local variant="$2"
  while IFS= read -r -d '' source_file; do
    if grep -Eq "package dev\.ainer\.(core|web|security|initializer|spring|starter|module)(\.|;)" "$source_file"; then
      fail "generated $variant project must not copy Ainer sources: $source_file"
    fi
  done < <(find "$source_root/src" -type f -name '*.java' -print0)
}

mkdir -p "$generated_dir"
run_cli init "$manifest" "$generated_dir"

# Determinism: regenerate into a fresh directory and compare byte-for-byte.
second_dir="$temporary_dir/second"
mkdir -p "$second_dir"
run_cli init "$manifest" "$second_dir"
diff -r "$generated_dir" "$second_dir" \
  || fail "regeneration is not deterministic (diff -r mismatch)"
run_cli diff "$manifest" "$generated_dir" >/dev/null \
  || fail "generated project bytes or execution modes differ from the manifest"

# 2. Generated project must not contain Ainer framework sources (only artifacts are referenced).
#    Framework packages are dev.ainer.core / dev.ainer.web / dev.ainer.security / dev.ainer.initializer;
#    the consumer's own package is dev.ainer.<groupId suffix> and is allowed.
grep -rq "dev.ainer" "$generated_dir/pom.xml" || fail "generated POM must reference Ainer artifacts"
reject_ainer_source_copies "$generated_dir" "plain"

# 3. The generated project must compile and its smoke test must run green
#    (ADR-0035 decision 6: consumer gate builds the project and starts the smoke
#    endpoint, with 0 skipped tests) through the generated project's own pinned wrapper.
cd "$generated_dir"
plain_wrapper="$generated_dir/mvnw"
[[ -x "$plain_wrapper" ]] || fail "generated Maven Wrapper is missing or not executable"
plain_maven_banner="$("$plain_wrapper" --version | sed -n '1p')"
[[ "$plain_maven_banner" == "Apache Maven 3.9.16"* ]] \
  || fail "generated wrapper must pin Maven 3.9.16 (got: $plain_maven_banner)"
"$plain_wrapper" --batch-mode --no-transfer-progress \
  "${maven_settings_args[@]}" \
  -Dmaven.repo.local="$local_repository" \
  -DskipTests \
  clean compile \
  || fail "generated consumer project failed to compile"

"$plain_wrapper" --batch-mode --no-transfer-progress \
  "${maven_settings_args[@]}" \
  -Dmaven.repo.local="$local_repository" \
  test \
  || fail "generated consumer smoke test failed"

plain_report="$generated_dir/target/surefire-reports"
plain_skipped=$(find "$plain_report" -name '*.txt' -exec grep -h 'Tests run:' {} \; \
  | awk -F, '{for (i=1; i<=NF; i++) if ($i ~ /Skipped/) {gsub(/[^0-9]/, "", $i); s += $i}} END {print s+0}')
[[ "$plain_skipped" == "0" ]] || fail "consumer smoke test must run with 0 skipped (got $plain_skipped)"

# 4. PostgreSQL variant: deterministic generation, no source copies, and a real
#    Testcontainers integration test run (0 skipped) against postgres:18.3-alpine.
pg_manifest="$temporary_dir/manifest-postgres.yaml"
pg_dir="$temporary_dir/generated-postgres"
pg_second="$temporary_dir/second-postgres"
mkdir -p "$pg_dir" "$pg_second"
{
  cat <<EOF
schemaVersion: v1
project:
  name: Initializer Postgres Gate
  groupId: dev.ainer.consumer
  artifactId: initializer-gate-pg
  version: 1.0.0
  description: generated by the Ainer Project Initializer postgres gate
spring-boot: 4.1.1
ainner: $ainner_version
java: 25
package: dev.ainer.consumer.gate.pg
database: postgresql
EOF
  if [[ "$ainner_version" == *-SNAPSHOT ]]; then
    printf 'allowSnapshot: true\n'
  fi
} >"$pg_manifest"

run_cli init "$pg_manifest" "$pg_dir"
run_cli init "$pg_manifest" "$pg_second"
diff -r "$pg_dir" "$pg_second" \
  || fail "postgres regeneration is not deterministic (diff -r mismatch)"
run_cli diff "$pg_manifest" "$pg_dir" >/dev/null \
  || fail "generated postgres bytes or execution modes differ from the manifest"

reject_ainer_source_copies "$pg_dir" "postgres"

grep -q "PostgreSQLContainer" $(find "$pg_dir/src/test" -name '*.java') \
  || fail "postgres variant must contain a Testcontainers integration test"
grep -q "AinerPostgresContainer.create()" $(find "$pg_dir/src/test" -name '*.java') \
  || fail "postgres variant must use the Ainer test-support PostgreSQL base"
grep -q "ainer-test-support" "$pg_dir/pom.xml" \
  || fail "postgres variant must depend on ainer-test-support"

cd "$pg_dir"
pg_wrapper="$pg_dir/mvnw"
[[ -x "$pg_wrapper" ]] || fail "generated postgres Maven Wrapper is missing or not executable"
"$pg_wrapper" --batch-mode --no-transfer-progress \
  "${maven_settings_args[@]}" \
  -Dmaven.repo.local="$local_repository" \
  -DskipTests \
  clean compile \
  || fail "generated postgres consumer project failed to compile"

"$pg_wrapper" --batch-mode --no-transfer-progress \
  "${maven_settings_args[@]}" \
  -Dmaven.repo.local="$local_repository" \
  test \
  || fail "generated postgres consumer integration tests failed"

pg_report="$pg_dir/target/surefire-reports"
skipped=$(find "$pg_report" -name '*.txt' -exec grep -h 'Tests run:' {} \; \
  | awk -F, '{for (i=1; i<=NF; i++) if ($i ~ /Skipped/) {gsub(/[^0-9]/, "", $i); s += $i}} END {print s+0}')
[[ "$skipped" == "0" ]] || fail "postgres consumer integration tests must run with 0 skipped (got $skipped)"

# 5. CRUD variant (ADR-0036): manifest with entities on the postgres variant.
#    Deterministic generation, no source copies, no code-generator dependency,
#    and a real PostgreSQL Testcontainers run of the CRUD lifecycle (0 skipped).
crud_manifest="$temporary_dir/manifest-crud.yaml"
crud_dir="$temporary_dir/generated-crud"
crud_second="$temporary_dir/second-crud"
mkdir -p "$crud_dir" "$crud_second"
{
  cat <<EOF
schemaVersion: v1
project:
  name: Initializer CRUD Gate
  groupId: dev.ainer.consumer
  artifactId: initializer-gate-crud
  version: 1.0.0
  description: generated by the Ainer Project Initializer CRUD gate
spring-boot: 4.1.1
ainner: $ainner_version
java: 25
package: dev.ainer.consumer.gate.crud
database: postgresql
entities:
  - name: product
    fields:
      - name: name
        type: string(64)
        comment: 产品名称
      - name: sku
        type: string(32)
        unique: true
        comment: 库存单位编码
      - name: price
        type: decimal
        nullable: true
      - name: active
        type: boolean
      - name: publishedAt
        type: instant
      - name: refId
        type: uuid
EOF
  if [[ "$ainner_version" == *-SNAPSHOT ]]; then
    printf 'allowSnapshot: true\n'
  fi
} >"$crud_manifest"

run_cli init "$crud_manifest" "$crud_dir"
run_cli init "$crud_manifest" "$crud_second"
diff -r "$crud_dir" "$crud_second" \
  || fail "CRUD regeneration is not deterministic (diff -r mismatch)"
run_cli diff "$crud_manifest" "$crud_dir" >/dev/null \
  || fail "generated CRUD bytes or execution modes differ from the manifest"

reject_ainer_source_copies "$crud_dir" "CRUD"

grep -q "mybatis-plus-generator" "$crud_dir/pom.xml" \
  && fail "CRUD variant must not depend on mybatis-plus-generator (hand-written templates only)"

grep -q "CrudIntegrationTest" $(find "$crud_dir/src/test" -name '*.java') \
  || fail "CRUD variant must contain a CRUD lifecycle integration test"

cd "$crud_dir"
crud_wrapper="$crud_dir/mvnw"
[[ -x "$crud_wrapper" ]] || fail "generated CRUD Maven Wrapper is missing or not executable"
"$crud_wrapper" --batch-mode --no-transfer-progress \
  "${maven_settings_args[@]}" \
  -Dmaven.repo.local="$local_repository" \
  -DskipTests \
  clean compile \
  || fail "generated CRUD consumer project failed to compile"

"$crud_wrapper" --batch-mode --no-transfer-progress \
  "${maven_settings_args[@]}" \
  -Dmaven.repo.local="$local_repository" \
  test \
  || fail "generated CRUD consumer integration tests failed"

crud_report="$crud_dir/target/surefire-reports"
crud_skipped=$(find "$crud_report" -name '*.txt' -exec grep -h 'Tests run:' {} \; \
  | awk -F, '{for (i=1; i<=NF; i++) if ($i ~ /Skipped/) {gsub(/[^0-9]/, "", $i); s += $i}} END {print s+0}')
[[ "$crud_skipped" == "0" ]] || fail "CRUD consumer integration tests must run with 0 skipped (got $crud_skipped)"

# 6. Manifest v2 secure vertical slice (ADR-0052): additive to v1 and intentionally
#    limited to simple-service + Workspace access control. The generated project must
#    carry explicit API/application/infrastructure boundaries, Workspace-bound SQL,
#    stable consumer errors, authorization-decision audit, protected OpenAPI and true-JWT
#    negative tests. It is compiled and tested outside the Ainer reactor with PostgreSQL.
secure_manifest="$temporary_dir/manifest-secure-v2.yaml"
secure_dir="$temporary_dir/generated-secure-v2"
secure_second="$temporary_dir/second-secure-v2"
mkdir -p "$secure_dir" "$secure_second"
{
  cat <<EOF
schemaVersion: v2
preset: simple-service
accessControl: workspace
errorNamespace: CATALOG
project:
  name: Initializer Secure V2 Gate
  groupId: dev.ainer.consumer
  artifactId: initializer-gate-secure
  version: 1.0.0
  description: generated by the Ainer Project Initializer secure v2 gate
spring-boot: 4.1.1
ainner: $ainner_version
java: 25
package: dev.ainer.consumer.gate.secure
database: postgresql
entities:
  - name: product
    fields:
      - name: name
        type: string(64)
        comment: 产品名称
      - name: sku
        type: string(32)
        unique: true
        comment: 工作空间内唯一库存单位编码
      - name: price
        type: decimal
        nullable: true
      - name: active
        type: boolean
      - name: publishedAt
        type: instant
      - name: refId
        type: uuid
EOF
  if [[ "$ainner_version" == *-SNAPSHOT ]]; then
    printf 'allowSnapshot: true\n'
  fi
} >"$secure_manifest"

run_cli init "$secure_manifest" "$secure_dir"
run_cli init "$secure_manifest" "$secure_second"
diff -r "$secure_dir" "$secure_second" \
  || fail "secure v2 regeneration is not deterministic (diff -r mismatch)"
run_cli diff "$secure_manifest" "$secure_dir" >/dev/null \
  || fail "generated secure v2 bytes or execution modes differ from the manifest"

reject_ainer_source_copies "$secure_dir" "secure v2"

secure_api_root="$secure_dir/src/main/java/dev/ainer/consumer/gate/secure/product/api"
secure_application_root="$secure_dir/src/main/java/dev/ainer/consumer/gate/secure/product/application"
secure_mapper="$secure_dir/src/main/java/dev/ainer/consumer/gate/secure/product/infrastructure/ProductMapper.java"
secure_migration="$secure_dir/src/main/resources/db/migration/V1__secure_initializer_gate_secure_product.sql"
secure_tests="$secure_dir/src/test/java"

[[ -d "$secure_api_root" && -d "$secure_application_root" && -f "$secure_mapper" ]] \
  || fail "secure v2 must generate explicit API/application/infrastructure boundaries"
grep -REq 'IPage|QueryWrapper|BaseMapper|ProductRow' "$secure_api_root" \
  && fail "secure v2 API layer must not expose MyBatis or persistence rows"
grep -REq 'IPage|QueryWrapper|BaseMapper' "$secure_application_root" \
  && fail "secure v2 application layer must not expose MyBatis abstractions"
grep -q 'WHERE workspace_id = #{workspaceId}' "$secure_mapper" \
  || fail "secure v2 resource SQL must carry an explicit workspace_id predicate"
grep -q 'AND version = #{expectedVersion}' "$secure_mapper" \
  || fail "secure v2 writes must enforce optimistic locking"
grep -q 'workspace_id uuid NOT NULL' "$secure_migration" \
  || fail "secure v2 resource and audit schema must carry workspace_id"
grep -q 'CATALOG.PRODUCT.ACCESS_DENIED' "$secure_application_root/ProductErrorCode.java" \
  || fail "secure v2 must generate a stable consumer-owned error namespace"
grep -q 'decision = '\''DENY'\''' $(find "$secure_tests" -name '*.java') \
  || fail "secure v2 must verify persisted authorization denial audit"
grep -q 'AINER.WORKSPACE.NOT_FOUND' $(find "$secure_tests" -name '*.java') \
  || fail "secure v2 must verify cross-membership access denial"
grep -q 'AINER.COMMON.UNAUTHENTICATED' $(find "$secure_tests" -name '*.java') \
  || fail "secure v2 must verify unauthenticated access denial"
grep -q '/v3/api-docs' $(find "$secure_tests" -name '*.java') \
  || fail "secure v2 must verify protected runtime OpenAPI"
grep -q 'JwtTestSupport.signUserJwt' $(find "$secure_tests" -name '*.java') \
  || fail "secure v2 integration tests must use a truly signed JWT"

cd "$secure_dir"
secure_wrapper="$secure_dir/mvnw"
[[ -x "$secure_wrapper" ]] || fail "generated secure v2 Maven Wrapper is missing or not executable"
"$secure_wrapper" --batch-mode --no-transfer-progress \
  "${maven_settings_args[@]}" \
  -Dmaven.repo.local="$local_repository" \
  -DskipTests \
  clean compile \
  || fail "generated secure v2 consumer project failed to compile"

"$secure_wrapper" --batch-mode --no-transfer-progress \
  "${maven_settings_args[@]}" \
  -Dmaven.repo.local="$local_repository" \
  test \
  || fail "generated secure v2 consumer integration tests failed"

secure_report="$secure_dir/target/surefire-reports"
secure_skipped=$(find "$secure_report" -name '*.txt' -exec grep -h 'Tests run:' {} \; \
  | awk -F, '{for (i=1; i<=NF; i++) if ($i ~ /Skipped/) {gsub(/[^0-9]/, "", $i); s += $i}} END {print s+0}')
[[ "$secure_skipped" == "0" ]] \
  || fail "secure v2 consumer integration tests must run with 0 skipped (got $secure_skipped)"

# 7. Existing-project additive integration: start from an already runnable secure-v2
#    consumer, preserve every existing byte, reserve V2 as an unrelated migration, then
#    plan/add a second entity at explicit V3. Repeating add must be idempotent. Because the
#    base project imports Authorization + Workspace, the generated JWT lifecycle also proves
#    the Workspace module policy contribution composes without hand-written workspace policy.
existing_manifest="$temporary_dir/manifest-existing-v2.yaml"
existing_dir="$temporary_dir/generated-existing-v2"
existing_reference="$temporary_dir/reference-existing-v2"
cp -R "$secure_dir" "$existing_dir"
rm -rf -- "$existing_dir/target"
printf 'SELECT 1;\n' >"$existing_dir/src/main/resources/db/migration/V2__existing_marker.sql"
cp -R "$existing_dir" "$existing_reference"

{
  cat <<EOF
schemaVersion: v2
preset: simple-service
accessControl: workspace
errorNamespace: CATALOG
project:
  name: Initializer Secure V2 Gate
  groupId: dev.ainer.consumer
  artifactId: initializer-gate-secure
  version: 1.0.0
spring-boot: 4.1.1
ainner: $ainner_version
java: 25
package: dev.ainer.consumer.gate.secure
database: postgresql
entities:
  - name: catalogEntry
    fields:
      - name: title
        type: string(120)
        comment: 增量目录条目标题
      - name: active
        type: boolean
EOF
  if [[ "$ainner_version" == *-SNAPSHOT ]]; then
    printf 'allowSnapshot: true\n'
  fi
} >"$existing_manifest"

run_cli plan-add "$existing_manifest" "$existing_dir" --migration-version 3 \
  | grep -q 'Flyway 起始版本 V3' \
  || fail "existing-project plan-add must report explicit V3"
[[ ! -e "$existing_dir/src/main/resources/db/migration/V3__secure_initializer_gate_secure_catalog_entry.sql" ]] \
  || fail "plan-add must remain read-only"

run_cli add "$existing_manifest" "$existing_dir" --migration-version 3 >/dev/null \
  || fail "existing-project additive integration failed"
second_add_output="$(run_cli add "$existing_manifest" "$existing_dir" --migration-version 3)" \
  || fail "existing-project repeated add failed"
grep -q '新增文件 0' <<<"$second_add_output" \
  || fail "existing-project repeated add must be idempotent"

while IFS= read -r -d '' reference_file; do
  relative="${reference_file#"$existing_reference"/}"
  cmp -s "$reference_file" "$existing_dir/$relative" \
    || fail "existing-project add modified an existing file: $relative"
done < <(find "$existing_reference" -type f -print0)

existing_migration="$existing_dir/src/main/resources/db/migration/V3__secure_initializer_gate_secure_catalog_entry.sql"
[[ -f "$existing_migration" ]] \
  || fail "existing-project add must generate the explicit V3 migration"
grep -q 'workspace_id uuid NOT NULL' "$existing_migration" \
  || fail "existing-project V3 migration must preserve workspace isolation"
grep -q 'AuthorizationModuleConfiguration.class' \
  "$existing_dir/src/main/java/dev/ainer/consumer/gate/secure/InitializerGateSecureApplication.java" \
  || fail "secure v2 base project must explicitly compose Authorization"
reject_ainer_source_copies "$existing_dir" "existing-project v2"

cd "$existing_dir"
existing_wrapper="$existing_dir/mvnw"
[[ -x "$existing_wrapper" ]] \
  || fail "existing-project Maven Wrapper is missing or not executable"
"$existing_wrapper" --batch-mode --no-transfer-progress \
  "${maven_settings_args[@]}" \
  -Dmaven.repo.local="$local_repository" \
  -DskipTests \
  clean compile \
  || fail "existing-project additive consumer failed to compile"

"$existing_wrapper" --batch-mode --no-transfer-progress \
  "${maven_settings_args[@]}" \
  -Dmaven.repo.local="$local_repository" \
  test \
  || fail "existing-project additive consumer integration tests failed"

existing_report="$existing_dir/target/surefire-reports"
existing_skipped=$(find "$existing_report" -name '*.txt' -exec grep -h 'Tests run:' {} \; \
  | awk -F, '{for (i=1; i<=NF; i++) if ($i ~ /Skipped/) {gsub(/[^0-9]/, "", $i); s += $i}} END {print s+0}')
[[ "$existing_skipped" == "0" ]] \
  || fail "existing-project consumer integration tests must run with 0 skipped (got $existing_skipped)"

echo "[ainer-initializer-consumer] $artifact_source initializer generation + consumer compile + postgres/CRUD/secure-v2/existing-project Testcontainers gate passed"
