#!/usr/bin/env bash
set -euo pipefail

boot_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
wrapper="$boot_root/mvnw"

fail() {
  echo "[ainer-initializer-consumer] ERROR: $*" >&2
  exit 1
}

configured_version="$(
  sed -n 's:.*<revision>\([^<]*\)</revision>.*:\1:p' "$boot_root/pom.xml" \
    | sed -n '1p'
)"
ainner_version="${AINER_VERSION:-$configured_version}"
[[ -n "$ainner_version" ]] \
  || fail "cannot determine the Ainer version; set AINER_VERSION explicitly"

[[ -x "$wrapper" ]] || fail "Maven Wrapper is missing or not executable: $wrapper"

temporary_parent="${TMPDIR:-/tmp}"
temporary_dir="$(mktemp -d "$temporary_parent/ainer-initializer-consumer.XXXXXX")"
local_repository="$temporary_dir/repository"
generated_dir="$temporary_dir/generated"
manifest="$temporary_dir/manifest.yaml"
cli_jar="$temporary_dir/initializer-cli.jar"

cleanup() {
  case "$temporary_dir" in
    "$temporary_parent"/ainer-initializer-consumer.*)
      rm -rf -- "$temporary_dir"
      ;;
    *)
      echo "[ainer-initializer-consumer] refusing unsafe cleanup target: $temporary_dir" >&2
      ;;
  esac
}
trap cleanup EXIT

cd "$boot_root"
"$wrapper" --batch-mode --no-transfer-progress \
  -Dmaven.repo.local="$local_repository" \
  -Drevision="$ainner_version" \
  -Dgpg.skip=true \
  -DskipTests \
  clean install

# 1. Deterministic generation: the same manifest must produce byte-identical output twice.
cat >"$manifest" <<EOF
schemaVersion: v1
project:
  name: Initializer Consumer Gate
  groupId: dev.ainer.consumer
  artifactId: initializer-gate
  version: 1.0.0
  description: generated by the Ainer Project Initializer gate
spring-boot: 4.1.0
ainner: $ainner_version
java: 25
package: dev.ainer.consumer.gate
EOF

if [[ "$ainner_version" == *-SNAPSHOT ]]; then
  printf 'allowSnapshot: true\n' >>"$manifest"
fi

cli_jar="$(find "$local_repository/dev/ainer/ainer-initializer-cli" -name '*-cli.jar' | head -n 1)"
[[ -n "$cli_jar" ]] || fail "ainner-initializer-cli shaded JAR was not installed"

run_cli() {
  java -jar "$cli_jar" "$@"
}

mkdir -p "$generated_dir"
run_cli init "$manifest" "$generated_dir"

# Determinism: regenerate into a fresh directory and compare byte-for-byte.
second_dir="$temporary_dir/second"
mkdir -p "$second_dir"
run_cli init "$manifest" "$second_dir"
diff -r "$generated_dir" "$second_dir" \
  || fail "regeneration is not deterministic (diff -r mismatch)"

# 2. Generated project must not contain Ainer framework sources (only artifacts are referenced).
#    Framework packages are dev.ainer.core / dev.ainer.web / dev.ainer.security / dev.ainer.initializer;
#    the consumer's own package is dev.ainer.<groupId suffix> and is allowed.
grep -rq "dev.ainer" "$generated_dir/pom.xml" || fail "generated POM must reference Ainer artifacts"
for source_file in "$generated_dir"/src/main/java/**/*.java "$generated_dir"/src/test/java/**/*.java; do
  [[ -f "$source_file" ]] || continue
  if grep -Eq "package dev\.ainer\.(core|web|security|initializer|spring|starter|module)(\.|;)" "$source_file"; then
    fail "generated project must not copy Ainer sources: $source_file"
  fi
done

# 3. The generated project must compile as an independent consumer (Maven 4 wrapper).
cd "$generated_dir"
"$wrapper" --batch-mode --no-transfer-progress \
  -Dmaven.repo.local="$local_repository" \
  -DskipTests \
  clean compile \
  || fail "generated consumer project failed to compile"

echo "[ainer-initializer-consumer] initializer generation + consumer compile gate passed"
